name: bdd-postgresql

services:
    postgres:
        image: postgres:17
        container_name: postgres-server

        restart: unless-stopped

        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

        ports:
            - "5432:5432"

        volumes:
            - ./data-postgres:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin

        restart: unless-stopped

        depends_on:
            - postgres

        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

        ports:
            - "8081:80"

        volumes:
            - ./data-pgadmin:/var/lib/pgadmin