name: bdd-mongodb

services:
    mongodb:
        image: mongo:8
        container_name: mongodb-server

        restart: unless-stopped

        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

        ports:
            - "27017:27017"

        volumes:
            - ./data-mongodb:/data/db

    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express

        restart: unless-stopped

        depends_on:
            - mongodb

        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            ME_CONFIG_MONGODB_SERVER: mongodb
            
            ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}

        ports:
            - "8082:8081"